packages:
  - docs
  - template
allowBuilds:
  "@parcel/watcher": false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
ignoredBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
minimumReleaseAgeExclude:
  - "@types/node@26.1.1"
  - "@typescript/typescript-aix-ppc64@7.0.2"
  - "@typescript/typescript-darwin-arm64@7.0.2"
  - "@typescript/typescript-darwin-x64@7.0.2"
  - "@typescript/typescript-freebsd-arm64@7.0.2"
  - "@typescript/typescript-freebsd-x64@7.0.2"
  - "@typescript/typescript-linux-arm64@7.0.2"
  - "@typescript/typescript-linux-arm@7.0.2"
  - "@typescript/typescript-linux-loong64@7.0.2"
  - "@typescript/typescript-linux-mips64el@7.0.2"
  - "@typescript/typescript-linux-ppc64@7.0.2"
  - "@typescript/typescript-linux-riscv64@7.0.2"
  - "@typescript/typescript-linux-s390x@7.0.2"
  - "@typescript/typescript-linux-x64@7.0.2"
  - "@typescript/typescript-netbsd-arm64@7.0.2"
  - "@typescript/typescript-netbsd-x64@7.0.2"
  - "@typescript/typescript-openbsd-arm64@7.0.2"
  - "@typescript/typescript-openbsd-x64@7.0.2"
  - "@typescript/typescript-sunos-x64@7.0.2"
  - "@typescript/typescript-win32-arm64@7.0.2"
  - "@typescript/typescript-win32-x64@7.0.2"
  - "@vue/language-core@3.3.7"
  - typescript@7.0.2
  - vue-tsc@3.3.7
