packages:
  - docs
  - template

allowBuilds:
  "@parcel/watcher": false
  esbuild: false
  unrs-resolver: false
  vue-demi: false

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi

overrides:
  undocs: link:.

minimumReleaseAgeExclude:
  - "nitro-nightly*"
  - crossws@0.4.12
  - db0@0.4.0 || 0.4.1
  - env-runner@0.2.0
  - h3@2.0.1-rc.29 || 2.0.1-rc.31
  - srvx@0.12.7 || 1.0.3
  - unstorage@2.0.0-alpha.9 || 2.0.0-alpha.10
  - nitro@3.0.260903-beta
