name: publish
on: { push: { branches: [main] } }
permissions: { id-token: write, contents: read }
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with: { fetch-depth: 0 }
      - run: npm i -fg corepack && corepack enable
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with: { node-version: 24, cache: "pnpm" }
      - run: pnpm install
      - run: pnpm changelogen --bump --canary nightly
      - run: npm publish --tag latest
